//! Tool input types: the parameter structs rmcp + schemars expose as
//! tool schemas, and their mappings onto `rutter-core` vocabulary.
//!
//! Boundary: pure data. These types know the spec's parameter shapes
//! (`docs/tool-catalog.md` §4) and nothing about the server, the session,
//! or the engine.

use rmcp::ErrorData as McpError;
use serde::{Deserialize, Serialize};

use rutter_core::action::ScrollDirection;
use rutter_core::cookie::{Cookie, SameSite};

/// Scroll directions accepted by the scroll tool.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, rmcp::schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum Direction {
    /// Toward the top of the page.
    Up,
    /// Toward the bottom of the page.
    Down,
    /// Toward the left edge.
    Left,
    /// Toward the right edge.
    Right,
}

impl From<Direction> for ScrollDirection {
    fn from(direction: Direction) -> Self {
        match direction {
            Direction::Up => Self::Up,
            Direction::Down => Self::Down,
            Direction::Left => Self::Left,
            Direction::Right => Self::Right,
        }
    }
}

/// Cross-site sending policy accepted by the set_cookies tool
/// (`docs/tool-catalog.md` §4: `strict|lax|none`).
#[derive(Debug, Clone, Copy, Serialize, Deserialize, rmcp::schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum SameSiteInput {
    /// Sent only in first-party contexts.
    Strict,
    /// Sent with top-level navigations.
    Lax,
    /// Sent cross-site (requires `secure`).
    None,
}

impl From<SameSiteInput> for SameSite {
    fn from(same_site: SameSiteInput) -> Self {
        match same_site {
            SameSiteInput::Strict => Self::Strict,
            SameSiteInput::Lax => Self::Lax,
            SameSiteInput::None => Self::None,
        }
    }
}

/// One cookie as agents set it (`docs/tool-catalog.md` §4).
#[derive(Debug, Clone, Serialize, Deserialize, rmcp::schemars::JsonSchema)]
pub struct CookieInput {
    /// Cookie name.
    pub name: String,
    /// Cookie value.
    pub value: String,
    /// Domain the cookie belongs to.
    pub domain: String,
    /// Path scope; when absent, the browser derives a default from the
    /// active page's URL.
    pub path: Option<String>,
    /// Secure-only flag; defaults to false.
    pub secure: Option<bool>,
    /// Http-only flag; defaults to false.
    pub http_only: Option<bool>,
    /// Cross-site policy: `strict`, `lax`, or `none`.
    pub same_site: Option<SameSiteInput>,
}

impl TryFrom<&CookieInput> for Cookie {
    type Error = McpError;

    fn try_from(input: &CookieInput) -> Result<Self, Self::Error> {
        Ok(Self {
            name: input.name.clone(),
            value: input.value.clone(),
            domain: input.domain.clone(),
            path: input.path.clone(),
            secure: input.secure.unwrap_or(false),
            http_only: input.http_only.unwrap_or(false),
            same_site: input.same_site.map(SameSite::from),
            expires: None,
        })
    }
}

/// Parameter sets; schemas are generated by rmcp + schemars.
#[derive(Debug, Serialize, Deserialize, rmcp::schemars::JsonSchema)]
/// Parameters of the navigate tool.
pub struct NavigateParams {
    /// Absolute URL to load.
    pub url: String,
}

#[derive(Debug, Serialize, Deserialize, rmcp::schemars::JsonSchema)]
/// Parameters for element-targeted tools.
pub struct ReferenceParams {
    /// Snapshot reference of the element, for example `e17`.
    pub reference: String,
}

#[derive(Debug, Serialize, Deserialize, rmcp::schemars::JsonSchema)]
/// Parameters of the `type` tool.
pub struct TypeParams {
    /// Snapshot reference of the element to focus.
    pub reference: String,
    /// Text to insert as literal characters.
    pub text: String,
}

#[derive(Debug, Serialize, Deserialize, rmcp::schemars::JsonSchema)]
/// Parameters of the press_key tool.
pub struct PressKeyParams {
    /// Key in engine notation, for example `a`, `Enter`, `Tab`.
    pub key: String,
}

#[derive(Debug, Serialize, Deserialize, rmcp::schemars::JsonSchema)]
/// Parameters of the select_option tool.
pub struct SelectOptionParams {
    /// Snapshot reference of the select element.
    pub reference: String,
    /// Values of the options to select.
    pub values: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize, rmcp::schemars::JsonSchema)]
/// Parameters of the scroll tool.
pub struct ScrollParams {
    /// Scroll direction.
    pub direction: Direction,
    /// Distance in pixels; must be greater than zero.
    pub amount: u32,
    /// Reference of a container to scroll; omitted scrolls the page.
    pub reference: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, rmcp::schemars::JsonSchema)]
/// Parameters of the wait_for tool.
pub struct WaitForParams {
    /// Text to wait for.
    pub text: String,
    /// Budget in milliseconds; default 10 000.
    pub timeout_ms: Option<u64>,
}

#[derive(Debug, Serialize, Deserialize, rmcp::schemars::JsonSchema)]
/// Parameters naming one open page.
pub struct PageParams {
    /// Page id as reported by tabs_list.
    pub page_id: String,
}

#[derive(Debug, Serialize, Deserialize, rmcp::schemars::JsonSchema)]
/// Parameters of the set_cookies tool.
pub struct CookiesParams {
    /// Cookies to set on this session's context.
    pub cookies: Vec<CookieInput>,
}
